/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @next/next/no-img-element */
// src/components/ProducCard.tsx

import React from "react";
// Import the Product type from the files you uploaded
import type { Product } from "../types/Product"; 
// Import UI components from the 'ui' folder
import Button from "./ui/Button"; 
import Badge from "./ui/badge"; 

// 1. Define the ProductItem interface (extends Product to include Mongo ID and name)
export interface ProductItem extends Product {
  name: string; // I assume the Mongoose model has a 'name' field
  _id: string; // The ID generated by MongoDB
}

// 2. Define the component's properties
interface ProductCardProps {
  item: ProductItem; // Product data to display
  onEditClick: (item: ProductItem) => void; // Handler for editing
  onToggle: (itemId: string, currentStatus: boolean) => void; // Handler for activating/deactivating
  onRemove: (itemId: string) => void; // Handler for deleting
  isUserAdmin: boolean; // Flag to determine the visibility of admin controls
}

/**
 * Componente funcional que muestra la información de un producto con controles de administración condicionales.
 */
const ProductCard: React.FC<ProductCardProps> = ({
  item,
  onEditClick,
  onToggle,
  onRemove,
  isUserAdmin,
}) => {
  // Simple logic for the Badge (Requirement 4.3)
  const badgeColor = item.isActive ? "ok" : "fail";
  const badgeText = item.isActive ? "Disponible" : "Agotado";

  // Price format (Requirement 3.4)
  const formattedPrice = `$${item.price.toFixed(2)}`;

  // Placeholder for the image with error handling
  const imageUrl = item.imageUrl || "https://placehold.co/400x160/1e293b/e2e8f0?text=SIN+IMAGEN";

  return (
    <div className="bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition duration-300 transform hover:-translate-y-1 border border-gray-100">
      
      {/* Image Display */}
      <div className="h-40 w-full bg-gray-100 flex items-center justify-center relative">
        <img
          src={imageUrl}
          alt={`Imagen de ${item.name}`}
          className="w-full h-full object-cover"
          // Fallback in case the image URL fails
          onError={(e) => {
            e.currentTarget.src = "https://placehold.co/400x160/1e293b/e2e8f0?text=ERROR+IMAGEN";
          }}
        />
        {/* Category Tag */}
        <span className="absolute top-2 right-2 px-3 py-1 text-xs font-semibold bg-indigo-500 text-white rounded-full shadow-md">
          {item.category}
        </span>
      </div>

      {/* Card Body */}
      <div className="p-5">
        <div className="flex justify-between items-start mb-2">
          <h3 className="text-lg font-bold text-gray-900 leading-tight pr-2">
            {item.name}
          </h3>
          {/* Display status Badge (Requirement 3.3) */}
          <Badge color={badgeColor as any}>{badgeText}</Badge>
        </div>

        <p className="text-gray-500 text-sm mb-3 font-mono">SKU: {item.sku}</p>

        <div className="flex justify-between items-center border-t pt-3 mt-3">
          <span className="text-2xl font-extrabold text-indigo-700">
            {formattedPrice}
          </span>
          <span className="text-md font-semibold text-gray-600">
            Stock: {item.quantity}
          </span>
        </div>

        {/* Admin Buttons (Conditional Rendering - Requirement 4.2) */}
        {isUserAdmin && (
          <div className="flex gap-2 mt-5 pt-3 border-t">
            <Button
              size="small"
              variant="secondary"
              onClick={() => onEditClick(item)}
              className="flex-1"
            >
              Editar
            </Button>
            <Button
              size="small"
              // Simple logic for button text and variant (Requirement 4.3)
              variant={item.isActive ? "toggle" : "primary"}
              onClick={() => onToggle(item._id, item.isActive)}
              className="flex-1"
            >
              {item.isActive ? "Desactivar" : "Activar"}
            </Button>
            <Button
              size="small"
              variant="delete"
              onClick={() => onRemove(item._id)}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm4 0a1 1 0 10-2 0v6a1 1 0 102 0V8z" clipRule="evenodd" />
              </svg>
            </Button>
          </div>
        )}
      </div>
    </div>
  );
};

export default ProductCard;